
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS_FB = " REGISTER_SUCCESS_FB";
export const REGISTER_SUCCESS_GOOGLE = " REGISTER_SUCCESS_GOOGLE";
export const LOGIN_SUCCESS = " LOGIN_SUCCESS";
export const LOGOUT = " LOGOUT";