export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const REMOVE_USER_PROFILE = "REMOVE_USER_PROFILE";
export const SET_CREATOR_PROFILE = "SET_CREATOR_PROFILE";
export const SET_UPDATE_PROFILE = "SSET_UPDATE_PROFILE";
export const SET_UPDATE_TOOLS = "SSET_UPDATE_TOOLS";
